#QTL mapping 
n_batches: 250
qtl_vcf: "/lustre/scratch117/cellgen/teamtrynka/lara/TregProject_Genotypes/BLUEPRINT_mimic_Imputation/All_Donors_Together/AllDonors_Imputed_AllAutosomes_MAF0.1_GRCh38_Setted.vcf.gz"
cis_window: 50000
nominal_cis_window: 50000
